#!/bin/bash

Today Monday, June 14. I'm home with Sasha I decided not to go to work so I can study and practicing on the projects.
But hopefully tomorrow I will be great day to work and make money.
I had an pointment with Stella, but looks like I will not be able to make it.